from sites_scrapers.get_response import get_response
from bs4 import BeautifulSoup as bs
import re

site_url = 'https://walmart.com/search?q=' 

def walmart(searcharg):
    try:
        search_argument = searcharg.replace(" ","+")
        response = get_response(site_url, search_argument)
        soup = bs(response.content, 'html.parser')
        products = soup.find_all('div', {'data-testid':'list-view'})

        items = []
        for product in products:
            if len(items) >= 5: # This means we only need 5 items so the loop goes untile it fills the items list with 5 items
                break
            
            title = product.find('span', {"data-automation-id":"product-title"})
            price = str(product.find('div', {"data-automation-id":"product-price"}).get_text()) #  the purpose of this piece of code is to extract a price in dollars from a specific HTML element with the attribute data-automation-id set to "product-price" on a web page. If the pattern is found, it extracts the price and stores it in the price variable. this text describing the code was generated by chat gpt 3.5
            match = re.search(r'\$(.*?)current', price)
            if match:
                price = match.group(1).strip()
            
            if title and price:
                items.append({'title':title.get_text(),'price':price})
            else:
                pass
    except:
        return []
    
    return items